name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSource: fromFile
      versionFilePath: .nvmrc

  - script: |
      sudo apt install -y libkrb5-dev
      npm ci
      npx playwright install --with-deps
    displayName: Install dependencies

  - script: yarn ts-node ./scripts/ci/build-monaco-editor-core-pkg stable
    displayName: Build monaco-editor-core
    continueOnError: true

  - script: yarn ts-node ./scripts/ci/build-monaco-editor-pkg stable
    displayName: Build monaco-editor
    continueOnError: true

  - script: |
      cd webpack-plugin
      npm ci
      npm run compile
    displayName: Build webpack plugin
    continueOnError: true
