name: CI

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: "https://npm.pkg.github.com"
          scope: "@${{ github.repository_owner }}"

      - name: Cache node modules
        id: cacheNodeModules
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-cacheNodeModules2-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: ${{ runner.os }}-cacheNodeModules2-

      - name: Install build tools
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          sudo apt update -y
          sudo apt install -y build-essential pkg-config libx11-dev libx11-xcb-dev libxkbfile-dev libnotify-bin libkrb5-dev

      - name: execute `npm ci` (1)
        if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
        run: |
          npm ci

      - name: Download Playwright
        run: npx playwright install --with-deps

      - name: execute `npm ci` (2)
        if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
        run: npm ci --prefix webpack-plugin

      # Build and publish monaco-editor-core
      - name: Setup, Build & Test monaco-editor-core
        run: yarn ts-node ./scripts/ci/build-monaco-editor-core-pkg stable
        env:
          VSCODE_REF: "main"

      - name: Configure npm for GitHub Packages (monaco-editor-core)
        run: |
          echo "@${GITHUB_REPOSITORY_OWNER}:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish monaco-editor-core to GitHub Packages
        run: npm publish --tag latest
        working-directory: ./dependencies/vscode/out-monaco-editor-core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Link monaco-editor-core
        run: npm link
        working-directory: ./dependencies/vscode/out-monaco-editor-core

      - name: Link monaco-editor-core
        run: npm link monaco-editor-core

      # Build and publish monaco-editor
      - name: Setup, Build & Test monaco-editor
        run: yarn ts-node ./scripts/ci/build-monaco-editor-pkg stable

      - name: Publish monaco-editor to GitHub Packages
        run: npm publish --tag latest
        working-directory: ./out/monaco-editor
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build and publish monaco-editor-webpack-plugin
      - name: Compile webpack plugin
        run: npm run compile --prefix webpack-plugin

      - name: Publish monaco-editor-webpack-plugin to GitHub Packages
        run: npm publish --tag latest
        working-directory: ./webpack-plugin
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
